### Problem 1

Load "the original dataset" from https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html into a pandas dataframe. (Hints: pandas.read_csv can read in a tab-separated file and information on the columns can be obtained from the brief description through the link above) 
1. What is the output variable for this dataset? (i.e. which variable is the one that a data scientist would predict, using this dataset?)
2. All the other columns in the dataset are the attributes. For each attribute: compute the mean and the standard deviation. For all of the attributes together, create a correlation matrix (Using Pearson correlation coefficients). Please use numpy and scipy methods. Next, calculate a correlation matrix using the pandas method (your dataframe variable name).corr. Did you get the same values?
3. Does it make sense to calculate the mean and standard deviation for all of the columns? Is the correlation meaningful? Why or why not?
4. Why is the main diagonal of the correlation coefficient equal to a vector of ones? Justify your answer

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv("https://www4.stat.ncsu.edu/~boos/var.select/diabetes.tab.txt", sep="\t")
df

     AGE  SEX   BMI      BP   S1     S2    S3    S4      S5   S6    Y
0     59    2  32.1  101.00  157   93.2  38.0  4.00  4.8598   87  151
1     48    1  21.6   87.00  183  103.2  70.0  3.00  3.8918   69   75
2     72    2  30.5   93.00  156   93.6  41.0  4.00  4.6728   85  141
3     24    1  25.3   84.00  198  131.4  40.0  5.00  4.8903   89  206
4     50    1  23.0  101.00  192  125.4  52.0  4.00  4.2905   80  135
..   ...  ...   ...     ...  ...    ...   ...   ...     ...  ...  ...
437   60    2  28.2  112.00  185  113.8  42.0  4.00  4.9836   93  178
438   47    2  24.9   75.00  225  166.0  42.0  5.00  4.4427  102  104
439   60    2  24.9   99.67  162  106.6  43.0  3.77  4.1271   95  132
440   36    1  30.0   95.00  201  125.2  42.0  4.79  5.1299   85  220
441   36    1  19.6   71.00  250  133.2  97.0  3.00  4.5951   92   57

[442 rows x 11 columns]

1. output variable: quantitative measure of disease progression one year after baseline

In [1]:
#1. Y is the output variable for the dataframe. Y is a measure of how far the disease has progressed in 1 year \
# after the initial data collection.

In [44]:
"""" 
2. All the other columns in the dataset are the attributes. 
For each attribute: compute the mean and the standard deviation. 
For all of the attributes together, create a correlation matrix 
(Using Pearson correlation coefficients). Please use numpy and scipy methods. 
Next, calculate a correlation matrix using the pandas method (your dataframe variable name).corr. 
Did you get the same values?
"""
my_corr = []
Y = df["Y"].values
mean_Y = np.mean(Y)
N = len(df)
mean = {}
std_dev = {}
corr = []


for (column_name, _) in df.iteritems():
    X = df[column_name].values
    mean[f"{column_name}"] = np.mean(X)
    std_dev[f"{column_name}"] = (np.sum((X - np.mean(X))**2))/(N-1)

print(f"mean: {mean}")
print(f"standard dev: {std_dev}")
print(np.array(df))

# Pearson product-moment correlation: [-1, +1] -1: 负相关 -> +1: 正相关

print("Correlation coefficient matrix (computed with numpy):") 
# np.corrcoef (Pearson product-moment correlation efficient) 
# https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
# 如何理解np.array(df).T：因为这里的研究对象是每一列数据，而原始数据是以row为变量的，所以需要转置
display(pd.DataFrame(np.corrcoef(np.array(df).T),columns=df.columns))

print("Correlation coefficient matrix (computed with pandas):")
display(df.corr())

mean: {'AGE': 48.51809954751131, 'SEX': 1.4683257918552035, 'BMI': 26.37579185520362, 'BP': 94.64701357466062, 'S1': 189.14027149321268, 'S2': 115.43914027149322, 'S3': 49.78846153846154, 'S4': 4.070248868778281, 'S5': 4.641410859728507, 'S6': 91.26018099547511, 'Y': 152.13348416289594}
standard dev: {'AGE': 171.84661043904742, 'SEX': 0.2495613630067412, 'BMI': 19.519798124377957, 'BP': 191.30440103836406, 'S1': 1197.7172407424507, 'S2': 924.9554940437713, 'S3': 167.2935853828711, 'S4': 1.6652609356563137, 'S5': 0.2728918982944973, 'S6': 132.16571243882169, 'Y': 5943.331347923785}
[[ 59.       2.      32.1    ...   4.8598  87.     151.    ]
 [ 48.       1.      21.6    ...   3.8918  69.      75.    ]
 [ 72.       2.      30.5    ...   4.6728  85.     141.    ]
 ...
 [ 60.       2.      24.9    ...   4.1271  95.     132.    ]
 [ 36.       1.      30.     ...   5.1299  85.     220.    ]
 [ 36.       1.      19.6    ...   4.5951  92.      57.    ]]
Correlation coefficient matrix (computed with numpy):

,AGE,SEX,BMI,BP,S1,S2,S3,S4,S5,S6,Y
0,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,0.187889
1,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.043062
2,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.586450
3,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.441482
4,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.212022
5,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.174054
6,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.394789
7,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.430453
8,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.565883
9,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.382483
10,0.187889,0.043062,0.586450,0.441482,0.212022,0.174054,-0.394789,0.430453,0.565883,0.382483,1.000000

Correlation coefficient matrix (computed with pandas):

,AGE,SEX,BMI,BP,S1,S2,S3,S4,S5,S6,Y
AGE,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,0.187889
SEX,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.043062
BMI,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.586450
BP,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.441482
S1,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.212022
S2,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.174054
S3,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.394789
S4,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.430453
S5,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.565883
S6,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.382483
Y,0.187889,0.043062,0.586450,0.441482,0.212022,0.174054,-0.394789,0.430453,0.565883,0.382483,1.000000

3. Does it make sense to calculate the mean and standard deviation for all of the columns? Is the correlation meaningful? Why or why not?
<br/>

_Ans:_
It does not truly make sense to calculate the mean or standard deviation for the SEX column. It is a categorical variable, and thus mean does not make sense. Furthermore, standard deviation is not useful, since there are no values besides 1 and 2.

4. Why is the main diagonal of the correlation coefficient equal to a vector of ones? Justify your answer

<br/>

_Ans_:
The main diagonal of the correlation coefficient is equal to a vector of ones because every variable has full correlation with itself.

### Problem 2

###### Part 1: Predict the values of the output variable you identified above.
1. Normalize all columns which it makes sense to normalize
2. Separate the entries into train and test segments randomly. Have the train segment contain 80%, about 354 entries. Let the test segment contain the remaining entries.
3. Use scikit-learn's linear regression algorithm to train on two columns of the train set, and test on the test set.
4. Use the linear regression algorithm to train on all the columns of the train set, and test on the test set.
5. Try different combinations of columns. See if you can find any combination that is better than using all of the columns.
6. Based on the values of MSE or R-squared of the train set and test set, what combination do you think is the best?

In [49]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

# It does not make sense to use linear regression on the sex column, so we drop it
diabetes = df.drop(columns = ['SEX'])

"""
1. Normalize all columns which it makes sense to normalize

Why normalizing data:

Standardization of a dataset is a common requirement for many machine learning estimators: they 
might behave badly if the individual features do not more or less look like standard normally 
distributed data (e.g. Gaussian with 0 mean and unit variance).

For instance many elements used in the objective function of a learning algorithm (such as the RBF 
kernel of Support Vector Machines or the L1 and L2 regularizers of linear models) assume that all 
features are centered around 0 and have variance in the same order. If a feature has a variance 
that is orders of magnitude larger that others, it might dominate the objective function and make 
the estimator unable to learn from other features correctly as expected.

"""
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
saved_cols = diabetes.columns
# Fits transformer to X and y (none for non-supervised transform) and returns a transformed version of X.
diabetes_arr = scaler.fit_transform(diabetes)
display(pd.DataFrame(diabetes_arr, columns=saved_cols))


"""
2. Separate the entries into train and test segments randomly. Have the train segment contain 80%, about 354 
entries. Let the test segment contain the remaining entries.
"""

from sklearn.model_selection import train_test_split

train, test = train_test_split(diabetes, test_size=0.2)
train_X = train.drop(columns = ["Y"])
train_y = train["Y"]
test_X = test.drop(columns = ["Y"])
test_y = test["Y"]


"""
3. Use scikit-learn's linear regression algorithm to train on two columns of the train set, 
and test on the test set.
"""
from sklearn.linear_model import LinearRegression
diab_pred = LinearRegression().fit(train_X[["AGE", "BP"]], train_y)
print("Result for Age and Blood Pressure", diab_pred.score(test_X[["AGE", "BP"]], test_y))


# Test for all columns
diab_pred = LinearRegression().fit(train_X, train_y)
print("Result for regressing on all columns",diab_pred.score(test_X, test_y))

# the larger the score the better

,AGE,BMI,BP,S1,S2,S3,S4,S5,S6,Y
0,0.800500,1.297088,0.459841,-0.929746,-0.732065,-0.912451,-0.054499,0.418531,-0.370989,-0.014719
1,-0.039567,-1.082180,-0.553505,-0.177624,-0.402886,1.564414,-0.830301,-1.436589,-1.938479,-1.001659
2,1.793307,0.934533,-0.119214,-0.958674,-0.718897,-0.680245,-0.054499,0.060156,-0.545154,-0.144580
3,-1.872441,-0.243771,-0.770650,0.256292,0.525397,-0.757647,0.721302,0.476983,-0.196823,0.699513
4,0.113172,-0.764944,0.459841,0.082726,0.327890,0.171178,-0.054499,-0.672502,-0.980568,-0.222496
...,...,...,...,...,...,...,...,...,...,...
437,0.876870,0.413360,1.256040,-0.119769,-0.053957,-0.602843,-0.054499,0.655787,0.151508,0.335904
438,-0.115937,-0.334410,-1.422086,1.037341,1.664355,-0.602843,0.721302,-0.380819,0.935254,-0.625064
439,0.876870,-0.334410,0.363573,-0.785107,-0.290965,-0.525441,-0.232934,-0.985649,0.325674,-0.261454
440,-0.956004,0.821235,0.025550,0.343075,0.321306,-0.602843,0.558384,0.936163,-0.545154,0.881318
441,-0.956004,-1.535374,-1.711613,1.760535,0.584649,3.654268,-0.830301,-0.088752,0.064426,-1.235408

Result for Age and Blood Pressure 0.20784630133697968
Result for regressing on all columns 0.49025308678231383

###### Part 2: Use Linear Regression on Quadratic Features
Use sklearn.preprocessing.PolynomialFeatures to expand the data set to include nonlinear elements, then perform linear regression again. Is this a better model comparing with the one you find in part 1?

reference:https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html

In [50]:
from sklearn.preprocessing import PolynomialFeatures
poly_transform = PolynomialFeatures(2)

In [51]:
# Transform data to have nonlinear interaction 
X = diabetes.drop(columns = ["Y"])
poly_diab_view = poly_transform.fit(X)
p_train_X = poly_diab_view.transform(train_X)
p_test_X = poly_diab_view.transform(test_X)

p_diab_pred = LinearRegression().fit(p_train_X, train_y)
print(p_diab_pred.score(p_test_X, test_y))

0.20092294693676804